### ISSUE TITLE
Website bad

### ISSUE THREAD

**Issue by pchung13** [robinchow/negative-prefs-website#3]
Does not work.

**Comment by pchung13** [comment]
![screenshot_20180314-222531](https://user-images.githubusercontent.com/1611478/37445752-eb974fe0-27d6-11e8-97d1-52039d8af348.png)

**Comment by robinchow** [comment]
Individual deployments are not the concern of this amazing project!

**Comment by robinchow** [comment]
(also it's fixed now)
